[styling.palette]
bg = "#010408"
surface = "#1F493E"
elevated = "#235867"
fg = "#C0CED7"
fg-muted = "#92AFBF"
primary = "#337084"
red = "#1F493E"
yellow = "#2E7159"
green = "#235867"
blue = "#337084"
